apiVersion: v2
appVersion: "1.7.3"
description: Wand installation chart
name: wand
type: application
version: 1.3.2
dependencies:
- alias: prometheus
  condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 27.11.0
- alias: kubeStateMetrics
  condition: kubeStateMetrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.33.*
- alias: nodeAgent
  condition: nodeAgent.enabled
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.45.*
