{{- if .Values.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "controller.fullname" . }}-metrics
  labels:
    app.kubernetes.io/name: {{ template "controller.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "controller.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: metrics
      port: 8080
      targetPort: 8080
{{- end }}