{{- if .Values.controller.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: wand-workload-defaults-protection
webhooks:
  - name: workload-defaults.wand.cloud
    clientConfig:
      service:
        name: {{ template "controller.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/validate-configmap"
        port: 9443
    rules:
      - operations: ["CREATE", "UPDATE", "DELETE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["configmaps"]
    objectSelector:
      matchLabels:
        wand.cloud/config-type: workload-defaults
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: {{ .Release.Namespace }}
    failurePolicy: Ignore
    sideEffects: None
    admissionReviewVersions: ["v1"]
{{- end }}
