{{- if and .Values.mutator.enabled .Values.mutator.generateCertificate }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "wand.fullname" . }}-admission-certgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
  labels:
    app.kubernetes.io/component: certgen
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ include "wand.fullname" . }}-admission-certgen
      labels:
        app.kubernetes.io/component: admission-certgen
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "wand.fullname" . }}-admission-certgen
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: create
          image: {{ printf "%s:%s" .Values.mutator.certGen.image.repository .Values.mutator.certGen.image.tag }}
          args:
            - create
            - --host={{ include "wand.fullname" . }}-mutator,{{ include "wand.fullname" . }}-mutator.{{ .Release.Namespace }}.svc
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ .Values.mutator.secretName }}
          resources:
            {{- toYaml .Values.mutator.certGen.resources | nindent 12 }}
          {{- with .Values.mutator.certGen.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.mutator.certGen.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mutator.certGen.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mutator.certGen.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mutator.certGen.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
