apiVersion: v1
kind: ConfigMap
metadata:
  name: wand-workload-settings-defaults
  labels:
    app.kubernetes.io/managed-by: wand
    wand.cloud/config-type: workload-defaults
data:
  defaults.yaml: |
    {{- .Values.workloadDefaults.config | toYaml | nindent 4 }}
