{{- if and .Values.mutator.enabled (not .Values.readOnlyMode) }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ template "mutator.fullname" . }}
webhooks:
  - name: mutator.wand.cloud
    clientConfig:
      {{- if not .Values.mutator.generateCertificate }}
      caBundle: {{ .Values.mutator.caBundle | default "" }}
      {{- end }}
      service:
        name: {{ template "mutator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
        port: 8443
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["*"]
        apiVersions: ["*"]
        resources: ["deployments", "statefulsets", "cronjobs", "daemonsets", "jobs"]
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["autoscaling"]
        apiVersions: ["v2"]
        resources: ["horizontalpodautoscalers"]
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["keda.sh"]
        apiVersions: ["v1alpha1"]
        resources: ["scaledobjects"]
    failurePolicy: Ignore
    sideEffects: None
    timeoutSeconds: 5
    admissionReviewVersions: ["v1", "v1beta1"]
    {{- if .Values.mutator.namespaceSelector }}
    namespaceSelector:
      {{- .Values.mutator.namespaceSelector | toYaml | nindent 6 }}
    {{- end }}
{{- end }}
