{{- if or .Values.controller.enabled (and .Values.mutator.enabled (not .Values.readOnlyMode)) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "wand.fullname" . }}-admission-certgen
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    "helm.sh/hook-weight": "-110"
    "argocd.argoproj.io/hook": Sync
    "argocd.argoproj.io/hook-delete-policy": BeforeHookCreation
    "argocd.argoproj.io/sync-wave": "-4"
  labels:
    app.kubernetes.io/component: admission-certgen
rules:
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - get
      - update
{{- end }}
