{{- if .Values.controller.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name:  {{ include "wand.fullname" . }}-admission-certgen-patch-controller
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/component: certgen
spec:
  ttlSecondsAfterFinished: 300
  template:
    metadata:
      name: {{ include "wand.fullname" . }}-admission-certgen-patch-controller
      labels:
        app.kubernetes.io/component: certgen
    spec:
      restartPolicy: OnFailure
      serviceAccountName: {{ include "wand.fullname" . }}-admission-certgen
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: patch
          image: {{ printf "%s:%s" .Values.webhookCert.certGen.image.repository .Values.webhookCert.certGen.image.tag }}
          imagePullPolicy: {{ .Values.webhookCert.certGen.image.pullPolicy }}
          args:
            - patch
            - --webhook-name=wand-workload-defaults-protection
            - --namespace={{ .Release.Namespace }}
            - --secret-name={{ .Values.webhookCert.secretName }}
            - --patch-validating=true
            - --patch-mutating=false
            - --log-level=debug
          resources:
            {{- toYaml .Values.webhookCert.certGen.resources | nindent 12 }}
          {{- with .Values.webhookCert.certGen.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.webhookCert.certGen.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhookCert.certGen.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhookCert.certGen.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhookCert.certGen.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
